[[CURRENCIES]]
code="FYLX"
issuer="GC6LAI2PZ57XQOGHO5VAHWCETUK7IB7MIKEZPYRZTDHNJSE44PVWGZ4X"
name="Fylox Protocol"
desc="FYLX is the native utility token of the Fylox ecosystem, powering cashback, governance, oracle rewards, premium access, and decentralized services on Pi Network."
image="https://fyloxprotocol.com/assets/fylx-logo.png"
